### ISSUE TITLE
Mailproxy does not have field or method 'Event Sink'

### ISSUE THREAD

**Issue by claucece** [katzenpost/kimchi#1]
Currently, it is reported that:

```
./main.go:459:20: p.EventSink undefined (type *mailproxy.Proxy has no field or method EventSink)
```

**Comment by david415** [comment]
@mixmasala why is mailproxy code being used? :) let's use the newer client instead.

**Comment by mixmasala** [comment]
vendoring is used to pin to specific branches (see: https://github.com/katzenpost/docs/blob/master/HACKING/index.rst); it's also possible the vendoring wasn't right - it should be fixed now in master.

@david415 I've removed the mailproxy dependency since we weren't currently using it in any tests. I'm planning on adding end-to-end tests using the new client library soon.

**Comment by claucece** [comment]
Thanks @mixmasala . I'll let you know if the error persists.

**Comment by claucece** [comment]
It seems fixed. I'm closing this.
